require 'elasticsearch/model'

# the 'ca_fingerprint' parameter
CERT_FINGERPRINT = 'd1ea91dfec519435098f5d2a85b1c473bbd1967a7569f3fdbb19f0986ad6af7e'

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "Ggwi5R4oCCuv70584zHj"

Elasticsearch::Model.client = Elasticsearch::Client.new(
  host: "https://elastic:Ggwi5R4oCCuv70584zHj@localhost:9200",
  transport_options: { ssl: { verify: false } },
  ca_fingerprint: CERT_FINGERPRINT
)
